// tools/build-offline.mjs — generate the optional file://-compatible build.
//
// The main index.html uses native ES modules, which browsers refuse to load
// from file:// origins. This script bundles js/app.js into one classic script
// (js/app.bundle.js) and writes index-offline.html that uses it, so the
// terminal can still be opened by double-clicking — same trick as a player
// running it from a USB stick.
//
// Usage:  npm i esbuild  (anywhere Node can resolve it), then:
//         node tools/build-offline.mjs
//
// Regenerate after any change under js/ (except js/legacy, which is shared).

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

let esbuild;
for (const resolver of [import.meta.url, '/tmp/']) {
    try {
        esbuild = createRequire(resolver)('esbuild');
        break;
    } catch (_) {}
}
if (!esbuild) {
    console.error('esbuild not found — run `npm i esbuild` first.');
    process.exit(1);
}

await esbuild.build({
    entryPoints: [path.join(ROOT, 'js/app.js')],
    bundle: true,
    format: 'iife',
    target: 'es2020',
    outfile: path.join(ROOT, 'js/app.bundle.js'),
    banner: { js: '/* GENERATED by tools/build-offline.mjs — do not edit. Source: js/app.js module graph. */' },
    logLevel: 'warning'
});

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8')
    .replace(
        '<script type="module" src="js/app.js"></script>',
        '<script src="js/app.bundle.js" defer></script>'
    )
    .replace(
        '<title>BLACK DESERT RESEARCH TERMINAL</title>',
        '<title>BLACK DESERT RESEARCH TERMINAL</title>\n    <!-- GENERATED by tools/build-offline.mjs for file:// use — edit index.html instead. -->'
    );
fs.writeFileSync(path.join(ROOT, 'index-offline.html'), html);

console.log('Wrote js/app.bundle.js and index-offline.html');
